"""init v0.1: 6 tables with task.rationale

Revision ID: 21aecfc7b53d
Revises: 
Create Date: 2026-04-20 19:47:33.570362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21aecfc7b53d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('daily_hours', sa.Float(), nullable=False),
    sa.Column('prefer_slots', sa.JSON(), nullable=False),
    sa.Column('weakness_rank', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('target_score', sa.Float(), nullable=False),
    sa.Column('current_estimate', sa.Float(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('detected_patterns', sa.JSON(), nullable=False),
    sa.Column('completion_rate', sa.Float(), nullable=False),
    sa.Column('avg_feeling', sa.Float(), nullable=False),
    sa.Column('module_distribution', sa.JSON(), nullable=False),
    sa.Column('suggestions_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_summary_user_id'), ['user_id'], unique=False)

    op.create_table('phase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('focus_modules', sa.JSON(), nullable=False),
    sa.Column('target_tasks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('actual_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('feeling', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("module IN ('listening', 'speaking', 'reading', 'writing')", name='ck_task_module'),
    sa.CheckConstraint("status IN ('pending', 'done', 'skipped', 'swapped')", name='ck_task_status'),
    sa.CheckConstraint('feeling IS NULL OR (feeling >= 1 AND feeling <= 5)', name='ck_task_feeling_range'),
    sa.ForeignKeyConstraint(['phase_id'], ['phase.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_user_id'), ['user_id'], unique=False)

    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('detail_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_ts'))

    op.drop_table('event')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_user_id'))
        batch_op.drop_index(batch_op.f('ix_task_date'))

    op.drop_table('task')
    op.drop_table('phase')
    with op.batch_alter_table('weekly_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_summary_user_id'))

    op.drop_table('weekly_summary')
    op.drop_table('goal')
    op.drop_table('user')
    # ### end Alembic commands ###
