"""v0.1 plus: learning_plan table + phase.plan_id

Revision ID: 476864d07e48
Revises: 21aecfc7b53d
Create Date: 2026-04-20 20:29:09.898736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '476864d07e48'
down_revision: Union[str, Sequence[str], None] = '21aecfc7b53d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_ai', sa.String(length=30), nullable=True),
    sa.Column('phases_data', sa.JSON(), nullable=False),
    sa.Column('resources', sa.JSON(), nullable=False),
    sa.Column('daily_habits', sa.JSON(), nullable=False),
    sa.Column('task_principles', sa.JSON(), nullable=False),
    sa.Column('checkpoints', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_plan_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('phase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_phase_plan_id'), ['plan_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_phase_plan_id_learning_plan',
            'learning_plan',
            ['plan_id'],
            ['id'],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phase', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_phase_plan_id_learning_plan', type_='foreignkey'
        )
        batch_op.drop_index(batch_op.f('ix_phase_plan_id'))
        batch_op.drop_column('plan_id')

    with op.batch_alter_table('learning_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_plan_user_id'))

    op.drop_table('learning_plan')
    # ### end Alembic commands ###
