"""v0.1 plus-dialog: drop task.module CheckConstraint

Revision ID: 4a4c50d65c00
Revises: 476864d07e48
Create Date: 2026-04-20 21:41:31.425682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a4c50d65c00'
down_revision: Union[str, Sequence[str], None] = '476864d07e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
