"""add learning_plan.daily_hours

Revision ID: df706cdc9e22
Revises: 4a4c50d65c00
Create Date: 2026-04-20 23:48:13.632944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df706cdc9e22'
down_revision: Union[str, Sequence[str], None] = '4a4c50d65c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_hours', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_plan', schema=None) as batch_op:
        batch_op.drop_column('daily_hours')

    # ### end Alembic commands ###
